# Generated by Django 4.2.16 on 2024-11-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="qq",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
