# Generated by Django 4.2.16 on 2024-11-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_customer_qq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="qq",
        ),
    ]
