# Generated by Django 4.2.16 on 2024-11-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_country_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="country",
        ),
        migrations.AddField(
            model_name="order",
            name="medicinelist",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
